spring.application.name=autosave
spring.jpa.hibernate.ddl-auto=update
spring.main.allow-bean-definition-overriding=true
server.port=8080

spring.datasource.url=${DB_URL_DEV}
spring.datasource.username=${DB_USER_DEV}
spring.datasource.password=${DB_PASSWORD_DEV}

spring.mail.host=${SMTP_HOST}
spring.mail.port=587
spring.mail.username=${SMTP_MAIL}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.url=${FRONTEND_URL}