spring.application.name=autosave
spring.jpa.hibernate.ddl-auto=validate
spring.main.allow-bean-definition-overriding=true
management.endpoints.web.exposure.include=startup
spring.main.lazy-initialization=true
spring.jpa.open-in-view=false
server.port=8080

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/postgres/migrations

org.neo4j.migrations.enabled=true
org.neo4j.migrations.locations-to-scan=classpath:db/neo4j/migrations

spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

spring.neo4j.uri=${NEO4J_URI}
spring.neo4j.authentication.username=${NEO4J_USER}
spring.neo4j.authentication.password=${NEO4J_PASSWORD}

app.jwt.token.secret=${JWT_TOKEN_SECRET}
app.jwt.token.expiration=${JWT_TOKEN_EXPIRATION}

app.mp.access.token=${MP_ACCESS_TOKEN}

spring.mail.host=${SMTP_HOST}
spring.mail.port=587
spring.mail.username=${SMTP_MAIL}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.url=${FRONTEND_URL}